version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: idosell-orders-backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/idosell
      - PORT=3000
      - API_TOKEN=change_me_secure_token
      - IDOSELL_API_KEY=${IDOSELL_API_KEY}
      - IDOSELL_API_HEADER_NAME=Authorization
      - IDOSELL_API_BASE=https://zooart6.yourtechnicaldomain.com
      - POLL_MINUTES=5
      - IDOSELL_FETCH_LIMIT=5000

volumes:
  mongo_data:
